# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- chmod +x build.sh
- chmod +x install.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh